services:
  - type: static
    name: symantrix365
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - action: rewrite
        source: /*
        destination: /index.html